export const AuthErrorCode = {
  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_TOO_MANY_ATTEMPTS: "OTP_TOO_MANY_ATTEMPTS",

  PHONE_ALREADY_REGISTERED: "PHONE_ALREADY_REGISTERED",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  PHONE_NOT_FOUND: "PHONE_NOT_FOUND",
  PHONE_NOT_VERIFIED: "PHONE_NOT_VERIFIED",

  AGE_CONFIRMATION_REQUIRED: "AGE_CONFIRMATION_REQUIRED",
  AGE_GATE_FAILED: "AGE_GATE_FAILED",
  PARENTAL_CONSENT_REQUIRED: "PARENTAL_CONSENT_REQUIRED",

  INVITE_TOKEN_INVALID: "INVITE_TOKEN_INVALID",
  INVITE_TOKEN_EXPIRED: "INVITE_TOKEN_EXPIRED",
  INVITE_TOKEN_USED_UP: "INVITE_TOKEN_USED_UP",

  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",

  JWT_INVALID: "JWT_INVALID",
  JWT_EXPIRED: "JWT_EXPIRED",

  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type AuthErrorCode = (typeof AuthErrorCode)[keyof typeof AuthErrorCode];
