export const AuthErrorCode = {
  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_TOO_MANY_ATTEMPTS: "OTP_TOO_MANY_ATTEMPTS",

  PHONE_ALREADY_REGISTERED: "PHONE_ALREADY_REGISTERED",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  PHONE_NOT_FOUND: "PHONE_NOT_FOUND",
  PHONE_NOT_VERIFIED: "PHONE_NOT_VERIFIED",

  AGE_CONFIRMATION_REQUIRED: "AGE_CONFIRMATION_REQUIRED",
  AGE_GATE_FAILED: "AGE_GATE_FAILED",
  PARENTAL_CONSENT_REQUIRED: "PARENTAL_CONSENT_REQUIRED",

  INVITE_TOKEN_INVALID: "INVITE_TOKEN_INVALID",
  INVITE_TOKEN_EXPIRED: "INVITE_TOKEN_EXPIRED",
  INVITE_TOKEN_USED_UP: "INVITE_TOKEN_USED_UP",

  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",

  JWT_INVALID: "JWT_INVALID",
  JWT_EXPIRED: "JWT_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",

  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // Consents
  INVALID_CONSENT_TYPE: "INVALID_CONSENT_TYPE",
  ALREADY_GRANTED: "ALREADY_GRANTED",
  ALREADY_REVOKED: "ALREADY_REVOKED",
  CONSENT_NOT_REVOCABLE: "CONSENT_NOT_REVOCABLE",

  // Feedback & Settings
  MESSAGE_REQUIRED: "MESSAGE_REQUIRED",
  CONFIRMATION_MISMATCH: "CONFIRMATION_MISMATCH",
} as const;

export type AuthErrorCode = (typeof AuthErrorCode)[keyof typeof AuthErrorCode];
